### ISSUE TITLE
Brick bug?

### ISSUE THREAD

**Issue by jtdaugherty** [sifmelcara/pgdl#6]
Hi! I was interested in looking at your `pgdl` code since you're using `brick`, and I noticed the comment here:
https://github.com/sifmelcara/pgdl/blob/master/src/Main.hs#L195
If there's anything I can do to help, let me know.  It isn't obvious to me from the comment what is going on, but if at some point you want to try reproducing the behavior in a smaller test program, I would love to track it down if there's a bug in the library.

**Comment by sifmelcara** [comment]
Thanks for reporting!
Here is a smaller program which can reproduce the problem

``` haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where

import qualified Data.Vector as V
import Data.Text (Text)
import Data.Maybe

import qualified Brick.Main as M
import qualified Brick.Widgets.Core as WC
import qualified Brick.Widgets.List as L
import qualified Brick.Widgets.Center as C
import qualified Brick.Types as T
import qualified Brick.Util as U
import qualified Brick.AttrMap as A
import qualified Graphics.Vty as V

ui l = [WC.vLimit 20 $ L.renderList l listDrawElement]
    where
    listDrawElement False num = WC.vLimit 3 . C.hCenter . C.vCenter . WC.str $ show num
    listDrawElement True num = WC.withAttr "selected" $ WC.vLimit 3 . C.hCenter . C.vCenter . WC.str $ show num


main :: IO ()
main = do
    let 
        theApp = M.App { M.appDraw = ui
                     , M.appChooseCursor = M.neverShowCursor
                     , M.appHandleEvent = appEvent
                     , M.appStartEvent = return
                     , M.appAttrMap = const theMap 
                     , M.appLiftVtyEvent = id
                     }
        theMap = A.attrMap V.defAttr [ ("selected", V.black `U.on` V.cyan)
                                     , (L.listAttr, V.white `U.on` V.magenta)
                                     ] 
        appEvent lst e = case e of
            V.EvKey V.KEsc [] -> M.halt lst
            ev -> M.continue =<< T.handleEvent ev lst
        l = L.list (T.Name "list") (V.fromList [1..30]) 3
    M.defaultMain theApp l
    return ()
```

The problem occurred when the item in the bottom of list is selected, for example:
![image](https://cloud.githubusercontent.com/assets/10496191/15447540/3821b188-1f0b-11e6-914f-424391373b32.png)
In the image above, we should be able to see partial content of item 16. (we should be able to see line 2 and line 3 of item 16)
a correct view looks like the follow image:
![image](https://cloud.githubusercontent.com/assets/10496191/15447561/ef47c366-1f0b-11e6-909b-ed1286652aea.png)

**Comment by jtdaugherty** [comment]
This should now be fixed in https://github.com/jtdaugherty/brick/commit/7682ee22f42e44a8484bad5a1d4769ac391e1221.  Give it a try!

**Comment by jtdaugherty** [comment]
(And thanks so much for that demo program; it really makes it so much easier for me to see the problem and test the fix!)

**Comment by sifmelcara** [comment]
I have tested it and it works well, thank you for your quick fix!

**Comment by jtdaugherty** [comment]
You're welcome. The fix is now released: http://hackage.haskell.org/package/brick-0.6.3

**Comment by sifmelcara** [comment]
By the way, the versions of `brick` in LTSHaskell and Stackage are quite old, is something going wrong with the dependencies? (I have no idea)

**Comment by jtdaugherty** [comment]
I don't know what's going on, either; I don't use those services and I've even been considering removing both `vty` and `brick` from them anyway.

**Comment by sifmelcara** [comment]
Ok, and thank you again for reporting this issue.
